### ISSUE TITLE
package.json version doesn't match github one

### ISSUE THREAD

**Issue by Tathanen** [vokal/css-reset#3]
@jrit maybe a 6.0.2 release with the matching version in package.json?  Unless you wanna delete and re-add the 6.0.1 with the update.  Maybe that.

**Comment by jrit** [comment]
resolved

**Comment by jrit** [comment]
note it was 1.0.1 -> 1.0.2, not version 6

**Comment by Tathanen** [comment]
Er... yes.  That.
